### ISSUE TITLE
Use the 3CL method for an online simulator

### ISSUE THREAD

**Issue by mcany78** [EDF-TREE/BuildSysPro#13]
Hi, I would like to know if it is possible to isolate the code that use the 3CL method for a free online simulator? 
The idea is to enrich an online property valuation simulator with EPC reports because today they have a huge impact on property prices in France. We want to help home owners to estimate their EPC for free and estimate how much renovation work they need to spend to move to a minimum of D, if possible C grade wheteher they stay in their property or need to sell it at the best market price.
I have a team of English speaking developers that can participate on this 3CL project.

**Comment by bcharrier** [comment]
Hi @mcany78,
Thank you for your message, I suggest to organize a meeting to discuss your needs and possible collaboration.
I send you a message on LinkedIn.
Best regards

**Comment by mcany78** [comment]
Hi Benoit,

Ok thanks, I am available Wednesday 28th June from2pm to 6pm and Thursday 29th June morning and afternoon (9am to 6pm).

Which time slot is the most convenient for you?

Best regards,

[A person wearing a suit and tie smiling at the camera  Description automatically generated]
Matthieu Cany
Co-fondateur
Tél: 0033 1 84 78 46 71
www.sextantfrance.fr<https://www.sextantfrance.fr/>
www.sextantproperties.com<https://www.sextantproperties.com/>
 [http://recrutement-immobilier.sextantfrance.fr/img_fr/sign3.jpg]
Tous les commerciaux du réseau Immobilier Sextant France sont des agents mandataires indépendants inscrits au registre spécial des agents commerciaux. Toutes les informations contenues dans cet email sont destinées à l'attention du ou des destinataire(s) mentionné(s) et aucune autre personne n'est autorisée à en prendre connaissance. Si vous n’êtes pas le destinataire de ce courrier électronique, merci d’en informer immédiatement l'auteur, en renvoyant ce courrier électronique à l’expéditeur et en supprimant ce courrier électronique et toutes les copies enregistrées dans votre système. Sextant France, SAS au capital de 100.556 € enregistrée au R.C.S Nanterre sous le nº 522 780 014. Code APE : 6831Z. Nº de TVA intracommunautaire : FR16522780014. Siège social: Sextant France, 183 avenue Charles de Gaulle, 92200, Neuilly sur Seine. Carte professionnelle Transaction sur immeuble et fonds de commerce CPI 7501 2018 000 037 419, délivrée par la CCI Paris Île-de-France le 01/07/2021. Absence de garantie financière, aucun maniement de fonds. RCP: Transaction sur immeubles et fonds de commerce : Liberty Mutual Insurance Europe, 42 Rue Washington, 75008 Paris 08.

**Comment by bcharrier** [comment]
Matthieu,
I will be out of office for the next 2 weeks, but feel free to book a confcall with us in July :
https://outlook.office365.com/owa/calendar/Synapse@edfonline.onmicrosoft.com/bookings/s/8oJb4D1NAk29_8v6wPWvZQ2
Best regards
