### ISSUE TITLE
sinh

### ISSUE THREAD

**Issue by thorade** [EDF-TREE/BuildSysPro#5]
The model [`BuildSysPro/BoundaryConditions/Solar/Utilities/SineH`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Solar/Utilities/SineH.mo) uses `sinh` as a variable name, but that is also the name for the function hyperbolic sine, defined in `Modelica.Math.sinh`. Not sure whether that might be a problem at some point.

**Comment by thorade** [comment]
Same problem in 
- [`BuildSysPro/BoundaryConditions/Weather/Functions/CalculTsky_withRH`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Weather/Functions/CalculTsky_withRH.mo)
- [`BuildSysPro/BoundaryConditions/Weather/Functions/CalculTsky_withoutRH`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Weather/Functions/CalculTsky_withoutRH.mo)
- [`BuildSysPro/BoundaryConditions/Solar/Irradiation/FLUXsurf`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Solar/Irradiation/FLUXsurf.mo)
- [`BuildSysPro/BoundaryConditions/Solar/Utilities/CosDirSunVector`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Solar/Utilities/CosDirSunVector.mo)
- [`BuildSysPro/BoundaryConditions/Solar/Utilities/CosDirSunVectorHeightAz`](https://github.com/edf-enerbat/BuildSysPro/blob/master/BuildSysPro/BoundaryConditions/Solar/Utilities/CosDirSunVectorHeightAz.mo)

and maybe some more:
https://github.com/edf-enerbat/BuildSysPro/search?utf8=%E2%9C%93&q=sinh

**Comment by bcharrier** [comment]
Hi @thorade 
Thank you for your observation. I'll change the name sinh into sin_h in all models.
