### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thorade** [EDF-TREE/BuildSysPro#6]
Please consider adding a LICENSE.md or LICENSE.txt file:
https://github.com/edf-enerbat/BuildSysPro/community

The Modelica Association has recently switched to the BSD 3-clause license:
https://github.com/modelica/ModelicaStandardLibrary/issues/2320
And the IBPSA library also switched:
https://github.com/ibpsa/modelica-ibpsa/issues/890

Maybe you also want to switch to the BSD 3-clause license, or another OSI certified license!?
https://choosealicense.com/appendix/
https://opensource.org/licenses

**Comment by sfroidurot** [comment]
Thank you for this comment.
As suggested, we created a *LICENSE.md* file containing the license details when we released the last version of the library.

Concerning the switch to the BSD 3-clause license, we are considering it. This is under investigation by our intellectual property specialist.

**Comment by pierre-haessig** [comment]
Hello,
I was just looking at the repo and it seems that [version 3.3.0](https://github.com/EDF-TREE/BuildSysPro/releases/tag/v3.3.0) fixes this issue.
Best, Pierre

**Comment by thorade** [comment]
Thanks, yes!
