### ISSUE TITLE
MassFlowRate conservation Radiators models

### ISSUE THREAD

**Issue by JFlamand1** [EDF-TREE/BuildSysPro#8]
Hi, 

I wanted to signal that I encountered some problems with hydraulic systems in the Library. Models HotWaterRadiator and HotWaterRadiatorRegul have problems with mass flowrate conservation. Regulation valve imply reduction of outlet flowrate, but inlet flowrate and the rest of the hydraulic loop is not corrected. Futhermore boiler and heatpump models don't generate error message when inlet flowrate is different from outlet flowrate ... It is a bit tricky for unexperimented users (maybe a warning in model documentation could help ?)

Best regards, 
J. Flamand

**Comment by Kodsgr** [comment]
done
